name: Smart Reminder

on:
  workflow_dispatch:

  schedule:
    - cron: '0 22 * * *'
      timezone: 'Asia/Kolkata'

    - cron: '30 0 * * *'
      timezone: 'Asia/Kolkata'

    - cron: '30 18 * * *'
      timezone: 'Asia/Kolkata'

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Send reminder email
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          EMAIL_TO: sureshbendaab40@gmail.com
        run: python reminder.py
